### ISSUE TITLE
Sound library error: unable to decode sound file bounce.wav

### ISSUE THREAD

**Issue by leathj** [processing/processing-sound#13] opened 2018-09-27 19:47 UTC
I recently opened a project from last school year and got the error above.  

The error below was also included: 
2018-09-27 15:43:26.764 java[18335:2483814] Error loading /Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea:  dlopen(/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea: no matching architecture in universal wrapper
	/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea: no matching architecture in universal wrapper
2018-09-27 15:43:26.764 java[18335:2483814] Cannot find function pointer iTeaHAL for factory 666438A7-7C20-4274-91D4-A7B71A71A40F in CFBundle/CFPlugIn 0x7f968c873380 </Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin> (bundle, not loaded)
Sep 27, 2018 3:43:26 PM com.jsyn.engine.SynthesisEngine start
INFO: Pure Java JSyn from www.softsynth.com, rate = 44100, RT, V16.8.0 (build 463, 2017-10-16)

**Comment by kevinstadler** [comment] 2018-09-28 08:49
I'm not sure what this *iTea* plugin is but it looks like it's some component of your computer's audio setup.

Either way, the error message you copied is not related to being unable to decode a sound file. Does the Sound plugin work, like can you hear anything? Can you post the output of calling `Sound.list();`?

**Comment by leathj** [comment] 2018-09-28 12:48
Hi,
 Currently I can't hear anything from this program.  Strangely enough, I can hear sound files on other programs written around the same time.

Sound.list(); presents me with the information below: 

Thank you, 
Jason


2018-09-28 08:45:40.997 java[29942:2888519] Error loading /Library/Audio/Plug-Ins/HAL/Digital Power Station.plugging/Contents/MacOS/iTea:  dlopen(/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea: no matching architecture in universal wrapper
	/Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin/Contents/MacOS/iTea: no matching architecture in universal wrapper
2018-09-28 08:45:40.997 java[29942:2888519] Cannot find function pointer iTeaHAL for factory 666438A7-7C20-4274-91D4-A7B71A71A40F in CFBundle/CFPlugIn 0x7fa0fde3aad0 </Library/Audio/Plug-Ins/HAL/Digital Power Station.plugin> (bundle, not loaded)
device id 0: Default Audio Device
  max inputs : 2   (default)
  max outputs: 2   (default)
device id 1: Built-in Microphone
  max inputs : 2
  max outputs: 0
device id 2: Built-in Output
  max inputs : 0
  max outputs: 2
device id 3: Adobe Media Encoder 4.0
  max inputs : 0
  max outputs: 0
device id 4: Elements Organizer 11.0
  max inputs : 0
  max outputs: 0
device id 5: Port Built-in Microphone
  max inputs : 0
  max outputs: 0
device id 6: Port Built-in Output
  max inputs : 0
  max outputs: 0
device id 7: Port Adobe Media Encoder 4.0
  max inputs : 0
  max outputs: 0
device id 8: Port Elements Organizer 11.0
  max inputs : 0
  max outputs: 0

**Comment by kevinstadler** [comment] 2019-03-17 11:30
Without any more information I'm gonna close this issue as it's probably a duplicate of #15 (seeing as the problem was with a particular WAV file)

**Closed as completed by kevinstadler** 2019-03-17 11:30 UTC
Labels: more info needed
