### ISSUE TITLE
count not work in processing.py mode

### ISSUE THREAD

**Issue by yonghuming** [processing/processing-sound#10] opened 2018-09-11 03:52 UTC
```
add_library('sound')
def setup():
    n = WhiteNoise(this)
    n.play()
```

**Comment by yonghuming** [comment] 2018-09-11 03:52
nothing happened

**Comment by yonghuming** [comment] 2018-09-11 03:52
```

import processing.sound.*; WhiteNoise noise;  void setup() {   size(640, 360);   background(255);      // Create the noise generator   noise = new WhiteNoise(this);   noise.play(); }        void draw() { }
--


```
![image](https://user-images.githubusercontent.com/435079/45337149-37876f00-b5b9-11e8-9842-743a058d1b7f.png)

**Comment by kevinstadler** [comment] 2018-09-12 09:55
@jdf can you help out here? I don't have processing.py set up so I can't reproduce

**Comment by kevinstadler** [comment] 2019-03-16 03:24
Seems to be a more general issue with external libraries in Processing.py. More information is available at #23, so closing this issue.

**Closed as completed by kevinstadler** 2019-03-16 03:24 UTC
Labels: more info needed, Processing.py
